server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      min: ${HTTP_MIN_THREADS:8}
      max: ${HTTP_MAX_THREADS:100}
      max-queue-capacity: ${HTTP_MAX_QUEUE:100}

logging:
  config: "classpath:logback-spring.xml"
  level:
    dev.alnat: ${BUSINESS_LOG_LEVEL:INFO}

spring:
  application:
    name: rate_limited_app
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      # small and fixed size DB pool is much preferred (see https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing)
      minimum-idle: ${DB_HIKARI_MIN_IDLE:4}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:4}
      auto-commit: ${DB_HIKARI_AUTO_COMMIT:false}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:30000}
      pool-name: db-hikari-pool
      validation-timeout: ${DB_VALIDATION_TIMEOUT:10000}
  transaction:
    default-timeout: ${DEFAULT_TRANSACTION_TIMEOUT:10}
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    validate-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  jackson:
    serialization:
      WRITE_DATE_KEYS_AS_TIMESTAMPS: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB_NUM:0}
      password: ${REDIS_PASSWORD:}
      connect-timeout: ${REDIS_CONNECTION_TIMEOUT:PT10S}
      timeout: ${REDIS_READ_TIMEOUT:PT10S}
      client-type: lettuce

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  server:
    # Extract actuator to another jetty server for performance reason
    port: ${MANAGEMENT_SERVER_PORT:88}

springdoc:
  swagger-ui:
    # Sort docs in alpha order
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    supportedSubmitMethods: ${SWAGGER_OPERATIONS:"get", "post"}
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}
  cache:
    disabled: false
